### PR TITLE
Remove dark ribbons and make the font universally lighter

### PR DESCRIPTION
**Pull request by stasm**
This is based on #12.

### CODE REVIEW

**Comment by stasm** [comment]
screen shot 2017-10-11 at 18 18 37-fullpage

**Comment by stasm** [comment]
screen shot 2017-10-11 at 18 23 18-fullpage

**Comment by zbraniecki** [comment]
I think I prefer the contrasting background to separate sections, but I recognize that it's a matter of preference, so having three people makes it a perfect voting opportunity :)

@mathjazz 's call!

**Comment by stasm** [comment]
The design process doesn't lend itself well to the principles of voting. It requires vision and coherence. I'd like@mathjazz to be the design lead on this if he accepts and make the call on his own.

**Comment by stasm** [comment]
Thanks to both of you. I left the `div` structure of the ribbons intact for now in case it makes it easier to land further improvements.

**Pull request merged**
